"""
Level 3 BD-Mediated Pipeline Test.

Tests the full workflow using `bd` CLI:
1. Create task issues with DSL bodies via `bd create`
2. Wire dependencies via `bd dep`
3. Update issues with DSL results
4. Verify dependency tracking
5. Collect results and create summary

Agents talk DSL-to-DSL. Summary is a short NL highlight generated by the main agent.
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.dsl_parser import parse_dsl, DslParseError
from src.bd_runner import (
    bd_create, bd_show, bd_update_body, bd_close,
    bd_add_dep, bd_ready, bd_list, BdPipelineRunner
)


def cleanup():
    for issue in bd_list(label="test", status="all"):
        bd_close(issue.get("id", ""))


def test_create_and_parse():
    """Create task with DSL, update with result, parse back."""
    print("\n=== Test: Create, update, parse ===")

    body = """[task id=t1 type=code]
[goal]Add input validation to POST /users endpoint[/goal]
[file read=src/handlers/user.py]
[spec]
[field name=email required=true rule=format:email]
[field name=name required=true rule=length:max=100]
[/spec]
[output-artifact path=src/handlers/user.py]
[/task]

## Acceptance
[accept]
[check]Code implements validation rules[/check]
[check]All output files created[/check]
[/accept]"""

    tid = bd_create("Implement: Add input validation", body,
                    labels=["agent=coder", "test"],
                    acceptance=["Code implements validation rules"])
    assert tid, "Create failed"
    print(f"  Created: {tid}")

    # Update with result
    result = """[result id=t1 status=complete]
[artifact type=file path=src/handlers/user.py action=modified lines=+23]
[artifact type=file path=src/validation/user_schema.py action=created lines=18]
[added fn=validate_user_input in:RequestBody out:ValidationResult]
[complexity delta="+2cyclomatic"]
[/result]"""
    bd_update_body(tid, result)

    # Parse back
    runner = BdPipelineRunner()
    parsed = runner.get_result(tid)
    assert parsed["parsed_ok"], f"Parse failed: {parsed.get('error')}"
    assert parsed["status"] == "complete"
    assert len(parsed["artifacts"]) == 2
    print(f"  PASS: status={parsed['status']}, artifacts={len(parsed['artifacts'])}")

    bd_close(tid)


def test_dependencies():
    """Test parent -> child dependency."""
    print("\n=== Test: Dependencies ===")

    parent = bd_create("Parent", "[task id=t1 type=code]Implement X[/task]",
                       labels=["agent=coder", "test"])
    child = bd_create("Child", "[task id=t2 type=review]Review X[/task]",
                      labels=["agent=reviewer", "test"], deps=[parent])
    assert parent and child
    print(f"  Parent: {parent}, Child: {child}")

    bd_close(parent)
    print("  PASS: Parent closed, child unblocked")


def test_full_pipeline():
    """Full pipeline: create tasks, produce results, summarize."""
    print("\n=== Test: Full pipeline ===")

    runner = BdPipelineRunner(verbose=True)

    # Create tasks
    impl = runner.create_task("implement", "coder",
        """[task id=t1 type=code]
[goal]Add input validation to POST /users[/goal]
[file read=src/handlers/user.py]
[spec]
[field name=email required=true rule=format:email]
[field name=name required=true rule=length:max=100]
[/spec]
[output-artifact path=src/handlers/user.py]
[/task]

## Acceptance
[accept][check]Code implements validation[/check][/accept]""",
        labels=["schema=code-task"],
        acceptance=["Code implements validation"])

    review = runner.create_task("review", "reviewer",
        """[task id=t2 type=review]
[goal]Review validation code[/goal]
[context-ref id=t1.artifacts]
[focus areas="correctness,security,style"]
[/task]

## Acceptance
[accept][check]Code reviewed[/check][check]Verdict provided[/check][/accept]""",
        labels=["schema=review-task"], deps=[impl])

    test = runner.create_task("test", "tester",
        """[task id=t3 type=test]
[goal]Write and run tests[/goal]
[context-ref id=t1.artifacts]
[test-cases]
[case]valid input -> 200[/case]
[case]invalid email -> 422[/case]
[/test-cases]
[/task]

## Acceptance
[accept][check]Tests written[/check][check]Results documented[/check][/accept]""",
        labels=["schema=test-task"], deps=[impl])

    print(f"\n  Tasks: impl={impl}, review={review}, test={test}")

    # Produce results
    print("\n  --- Results ---")

    runner.update_result(impl, """[result id=t1 status=complete]
[artifact type=file path=src/handlers/user.py action=modified lines=+23]
[artifact type=file path=src/validation/user_schema.py action=created lines=18]
[added fn=validate_user_input in:RequestBody out:ValidationResult]
[/result]""")
    runner.complete_task(impl)

    runner.update_result(review, """[result id=t2 status=complete]
[verdict approve]
[finding severity=minor path=src/handlers/user.py:34]
Email regex does not support international domains.
[/finding]
[/result]""")
    runner.complete_task(review)

    runner.update_result(test, """[result id=t3 status=complete]
[artifact type=file path=tests/test_validation.py action=created lines=45]
[test-suite total=8 pass=7 fail=1]
[test name=test_valid status=pass]
[test name=test_invalid_email status=pass]
[test name=test_missing_name status=pass]
[test name=test_age_boundary status=pass]
[test name=test_age_high status=pass]
[test name=test_age_low status=pass]
[test name=test_concurrent status=pass]
[test name=test_sql_injection status=fail reason="SQL chars not sanitized"]
[/test-suite]
[/result]""")
    runner.complete_task(test)

    # Collect and summarize
    print("\n  --- Summary ---")
    results = runner.collect_results([impl, review, test])
    assert all(r["parsed_ok"] for r in results)

    for r in results:
        a = len(r.get("artifacts", []))
        print(f"  {r['bd_id']}: {r['status']}, {a} artifacts")

    # Generate summary prompt (in production, main agent LLM generates this)
    prompt = runner.build_summary_prompt(results)
    print(f"\n  Summary prompt:\n{prompt}")

    # Create summary issue
    summary_body = """## Summary

All tasks completed.

- **Coder**: Implemented input validation (2 files, +41 lines, validate_user_input added)
- **Reviewer**: Approved with 1 minor finding (email regex doesn't support international domains)
- **Tester**: 7/8 pass, 1 fail (SQL chars not sanitized in name field)

## Action Items

- Use email-validator library for international domains
- Add SQL sanitization for name field"""

    sid = runner.create_summary("Summary: Add input validation", summary_body)
    print(f"  Summary: {sid}")

    # Verify
    info = bd_show(sid)
    stored = info.get("description", "")
    assert "Summary" in stored
    print("  PASS: Summary created")

    return True


def main():
    print("=" * 60)
    print("BD Pipeline Integration Test")
    print("=" * 60)
    cleanup()

    try:
        test_create_and_parse()
        test_dependencies()
        test_full_pipeline()
        ok = True
    except Exception as e:
        print(f"\n  FAIL: {e}")
        import traceback; traceback.print_exc()
        ok = False
    finally:
        cleanup()

    print(f"\n{'=' * 60}\nOverall: {'PASS' if ok else 'FAIL'}\n{'=' * 60}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
